services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: mapfind-app
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mapfind-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:7
        container_name: mapfind-redis
        ports:
            - "6379:6379"
    vite:
        image: node:20
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:cached
            - vendor:/var/www/html/vendor
        command: sh -c "npm run dev"
        ports:
            - "${VITE_PORT:-5173}:5173"
        depends_on:
            - app
volumes:
    dbdata:
    vendor:
