version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "D5:83:3c:d6:bf:65:c3:85:e6:c8:a9:aa:77:f6:d4:72:a4"
      - run:
          name: Configure Git Exception
          command: ssh -o StrictHostKeyChecking=no clem@45.147.98.97 "git config --global --add safe.directory /var/www/mapfind.app"
      - run:
          name: Deploy to Server
          command: |
            export GIT_TERMINAL_PROMPT=0
            ssh -o StrictHostKeyChecking=no clem@45.147.98.97 "cd /var/www/mapfind.app && git reset --hard origin/main && git pull && composer install && php artisan test && php artisan storage:link && php artisan migrate --force && npm install && npm run build && php artisan filament:upgrade"
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
